--PREGUNTA 1
CREATE TABLE CITAS_MEDICAS (
    CITA_ID           NUMBER CONSTRAINT PK_CITAS_MEDICAS PRIMARY KEY,
    PACIENTE_ID       NUMBER NOT NULL,
    PERSONAL_ID       NUMBER NOT NULL,
    FECHA_CITA        DATE NOT NULL,
    HORA_CITA         DATE NOT NULL,
    ESTADO            VARCHAR2(20) DEFAULT 'Programada'
);

--PREGUNTA 2
CREATE TABLE RESULTADOS_LABORATORIO (
    RESULTADO_ID      NUMBER CONSTRAINT PK_RESULTADOS_LABORATORIO PRIMARY KEY,
    ATENCION_ID       NUMBER NOT NULL,
    TIPO_PRUEBA       VARCHAR(100) NOT NULL,
    FECHA_RESULTADO   DATE NOT NULL,
    VALOR_RESULTADO   VARCHAR2(100) NOT NULL
);

--PREGUNTA 3
COMMENT ON COLUMN BOLETAS.BOLETA_ID        IS 'Identificador único de la boleta de pago.';
COMMENT ON COLUMN BOLETAS.PACIENTE_ID      IS 'Paciente asociado a la boleta.';
COMMENT ON COLUMN BOLETAS.FECHA_EMISION    IS 'Fecha en que se emitió la boleta.';
COMMENT ON COLUMN BOLETAS.MONTO_TOTAL      IS 'Monto total facturado.';
COMMENT ON COLUMN BOLETAS.METODO_PAGO      IS 'Método de pago utilizado (efectivo, tarjeta, etc.).';
COMMENT ON COLUMN BOLETAS.NRO_SERIE         IS 'Número de serie de la boleta.';

--PREGUNTA 4
CREATE TABLE INVENTARIO_MEDICAMENTOS (
    INVENTARIO_ID   NUMBER CONSTRAINT PK_INVENTARIO_MEDICAMENTOS PRIMARY KEY,
    MEDICAMENTO_ID  NUMBER NOT NULL,
    UBICACION       VARCHAR2(100) NOT NULL,
    CANTIDAD        NUMBER
);

--PREGUNTA 5
ALTER TABLE INVENTARIO_MEDICAMENTOS
    ADD CONSTRAINT PK_MEDICAMENTO_INVENTARIO
        FOREIGN KEY (MEDICAMENTO_ID)
        REFERENCES MEDICAMENTOS(MEDICAMENTO_ID);

--PREGUNTA 6
ALTER TABLE PACIENTES
    DROP COLUMN APELLIDOS;

ALTER TABLE MEDICAMENTOS
    ADD PRIMER_APELLIDO VARCHAR2(50) NOT NULL;
    
ALTER TABLE MEDICAMENTOS
    ADD SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL;

--PREGUNTA 7
ALTER TABLE CITAS_MEDICAS
    ADD CONSTRAINT PK_PACIENTES_CITAS_MEDICAS
        FOREIGN KEY (PACIENTE_ID)
        REFERENCES PACIENTES(PACIENTE_ID);
ALTER TABLE CITAS_MEDICAS
    ADD CONSTRAINT PK_PERSONAL_CITAS
        FOREIGN KEY (PERSONAL_ID)
        REFERENCES PERSONALES_MEDICOS(PERSONAL_ID);

--PREGUNTA 8
ALTER TABLE RESULTADOS_MEDICAMENTOS
    ADD CONSTRAINT PK_ATENCIONES_RESULTADOS
        FOREIGN KEY (ATENCION_ID)
        REFERENCES ATENCIONES_MEDICAS(ATENCION_ID);
        
--PREGUNTA 9
ALTER TABLE PACIENTES
    ADD CONSTRAINT CK_PACIENTES_GENERO CHECK (SEXO='M' OR SEXO='F');

--PREGUNTA 10
ALTER TABLE RECETAS_MEDICAMENTOS
    ADD CONSTRAINT CK_RECETAS_POSITIVO CHECK (CANTIDAD_DOSIS>0);

ALTER TABLE BOLETAS
    ADD CONSTRAINT CK_BOLETAS_POSITIVO CHECK (MONTO_TOTAL>0);

--PREGUNTA 11







