--PREGUNTA 1
CREATE TABLE COM_CLIENTES(
    CLIENTE_ID            NUMBER CONSTRAINT PK_COM_CLIENTES PRIMARY KEY,
    RAZON_SOCIAL          VARCHAR2(150) NOT NULL,
    RUC                   VARCHAR2(11) NOT NULL,
    DIRECCION             VARCHAR2(200) NOT NULL,
    TELEFONO              VARCHAR2(20),
    CORREO                VARCHAR2(100),
    EJECUTIVO_ID          NUMBER NOT NULL,
    ACTIVO                NUMBER(1) NOT NULL,
    USUARIO_CREACION      VARCHAR2(50) NOT NULL,
    FECHA_ACTUALIZACION   DATE,
    USUARIO_ACTUALIZACION VARCHAR2(50)
);

--PREGUNTA 2
COMMENT ON COLUMN COM_CLIENTES.CLIENTE_ID             IS 'Identificador único del cliente mayorista';
COMMENT ON COLUMN COM_CLIENTES.RAZON_SOCIAL           IS 'Razón social o nombre comercial del cliente';
COMMENT ON COLUMN COM_CLIENTES.RUC                    IS 'RUC del cliente, 11 dígitos numéricos, debe ser único';
COMMENT ON COLUMN COM_CLIENTES.DIRECCION              IS 'Dirección fiscal del cliente';
COMMENT ON COLUMN COM_CLIENTES.TELEFONO               IS 'Teléfono principal del cliente';
COMMENT ON COLUMN COM_CLIENTES.CORREO                 IS 'Correo electrónico de contacto del cliente';
COMMENT ON COLUMN COM_CLIENTES.EJECUTIVO_ID           IS 'Identificador del ejecutivo de ventas';
COMMENT ON COLUMN COM_CLIENTES.ACTIVO                 IS 'Indicador de estado: 1=activo, 0=inactivo';
COMMENT ON COLUMN COM_CLIENTES.USUARIO_CREACION       IS 'Usuario que creó el registro';
COMMENT ON COLUMN COM_CLIENTES.FECHA_ACTUALIZACION    IS 'Fecha de la última modificación';
COMMENT ON COLUMN COM_CLIENTES.USUARIO_ACTUALIZACION  IS 'Usuario que realizó la última modificación';

--PREGUNTA 3
ALTER TABLE COM_CLIENTES
    ADD CONSTRAINT FK_CLIENTES_EJECUTIVOS FOREIGN KEY (EJECUTIVO_ID)
        REFERENCES COM_EJECUTIVOS(EJECUTIVO_ID);

ALTER TABLE COM_CONDICIONES_PAGO
    ADD CLIENTE_ID NUMBER CONSTRAINT FK_CONDICIONES_PAGO_CLIENTES
        REFERENCES COM_CLIENTES(CLIENTE_ID);
    
ALTER TABLE COM_PEDIDOS
    ADD CLIENTE_ID NUMBER CONSTRAINT FK_PEDIDOS_CLIENTES
        REFERENCES COM_CLIENTES(CLIENTE_ID);

ALTER TABLE COM_CLIENTES
    ADD CONSTRAINT UQ_CLIENTES_RUC UNIQUE(RUC);

--PREGUNTA 4
ALTER TABLE COM_EJECUTIVOS
    MODIFY NOMBRES   VARCHAR(60);

ALTER TABLE COM_EJECUTIVOS
    MODIFY APELLIDOS VARCHAR(60);
    
--PREGUNTA 5
ALTER TABLE COM_EJECUTIVOS
    ADD CELULAR NUMBER NOT NULL;

ALTER TABLE COM_PROVEEDORES 
    ADD CORREO VARCHAR2(100) NOT NULL;

ALTER TABLE CAT_FICHAS_TECNICAS
    ADD FECHA_CREACION DATE NOT NULL;

ALTER TABLE COM_DETALLES_PEDIDOS
    ADD DET_PEDIDO_ID NUMBER(10) CONSTRAINT PK_DETALLES_PEDIDOS PRIMARY KEY;

ALTER TABLE COM_CLIENTES 
    ADD FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL;
    
ALTER TABLE COM_CLIENTES
    ADD MAXIMO_CREDITO NUMBER(7,2) NOT NULL CONSTRAINT CK_CLIENTES_RANGO CHECK (MAXIMO_CREDITO>=1000 AND MAXIMO_CREDITO<10000);

--PREGUNTA 6
ALTER TABLE COM_CLIENTES
    RENAME COLUMN DIRECCION TO DIRECCION_CLIENTES;

ALTER TABLE COM_CLIENTES
    RENAME COLUMN TELEFONO TO TELEFONO_CLIENTE;
    
--PREGUNTA 7
ALTER TABLE COM_CLIENTES
    DROP COLUMN CORREO;

ALTER TABLE CAT_MODELOS
    DROP COLUMN IND_IMPORTADO;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
